### ISSUE TITLE
[MinGW] Cant install, no package 'gio-unix-2.0' found

### ISSUE THREAD

**Issue by hugonun** [tiliado/valacef#15]
When trying to configure, I get the following:

```
Checking for 'gio-unix-2.0'
['C:\\msys32\\mingw64\\bin/pkg-config.exe', '--cflags', '--libs', 'gio-unix-2.0']
err: Package gio-unix-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gio-unix-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gio-unix-2.0' found
```

I have msys/glib2 2.54.3-1 installed, I believe they renamed it to gio-windows-2.0.

**Comment by fenryxo** [comment]
Hello @hugonun. The glib library provides many modules such as `gio-2.0` (platform-agnostic IO), `gio-unix-2.0` (IO specific to Unix), `gio-windows-2.0` (IO specific to Windows), etc.

Since you are building for windows, `gio-unix-2.0` is not available. You could try removing [the `pkgconfig(ctx, 'gio-unix-2.0', 'UNIXGIO', MIN_GLIB)` check](https://github.com/tiliado/valacef/blob/master/wscript#L140) and see what happens. However, building ValaCEF on Windows isn't supported.

**Comment by hugonun** [comment]
Thanks for helping me out, but it turns out I get stuck completely with the x11 part.
